### ISSUE TITLE
Complete hang

### ISSUE THREAD

**Issue by drwonky** [ndbeals/winssh-pageant#22] opened 2022-07-14 21:29 UTC
Hello,

I installed the OpenSSH package from the Win32-OpenSSH repo as directed in the README.  I added it to the PATH.  I then started winssh-pageant.exe and tried to use MobaXterm and PuTTY, but both hang when they try to talk to Pageant (proxy).

I confirmed the named pipes a present and that `ssh-add -l` works fine in Powershell.

This is a Windows 10 VM with various nannies installed to protect it.

I'm at a loss as to what the hang is caused by.  I'm assuming there is a failure to communicate (i/o blocking).

Relevant pipes:
```
\\.\pipe\openssh-ssh-agent
\\.\pipe\pageant.USERNAME.1a631cca5dbd4ff4c28f70c6cbcb1a2aa0c7f32e5b906367e1e9f85177e22b4d
```

**Comment by drwonky** [comment] 2022-07-14 21:51
More info:
Using ssh-pageant in cygwinx works, but if I try to use MobaXterm or PuTTY, they hang *and* ssh-pageant fails to work after that.

**Comment by ndbeals** [comment] 2022-07-29 04:13
Thanks for the issue report, I'll look into this further, which version of putty are you using?

**Comment by drwonky** [comment] 2022-07-29 07:08
Putty 0.76

**Comment by andreisolo0** [comment] 2022-08-04 15:02
Same issue here, after a first SSH login with success any other connection hangs.

**Comment by tsuchim** [comment] 2022-09-09 21:24
The same problem occurs in my version 0.77 on Windows10 environment.

**Comment by 1Dragoon** [comment] 2022-11-11 04:25
The problem is the win32 callback is hanging while waiting for the pipe. Sometimes that can be caused by problems with your agent, sometimes it's because we're not properly handling an agent error response and then waiting indefinitely for further data that will never come. #23 fixes the reasons I've run into this problem, though YMMV.

**Comment by ndbeals** [comment] 2022-12-16 06:17
This should be fixed with the latest release, find it here: https://github.com/ndbeals/winssh-pageant/releases/tag/v2.3.0

**Closed by ndbeals** 2022-12-16 06:17 UTC
